### ISSUE TITLE
add documentation about Zoom levels and STAC Assets

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler-stacapi#3]
When using the `/collections` mosaics, the tiler has no knowledge about the STAC Collection and Items metadata so a `tilejson` request will return `minzoom=0`, `maxzoom=24` and `bbox=-180, -90, 180, 90`

When using ☝️ in an application (map or QGIS) this will mostly kill the raster service (and potentially request a large /search query to the STAC API (e.g. searching items for a tile 0,0,0, covering the whole world). 

when using `/tilejson.json`, `/map` or `/WMTSCapabilities.xml` endpoints the user can (should?) pass the min/max zoom and bbox in order to limit the tile coverage.

But to know those values, the user needs to have a basic knowledge of the items stored in a collection. 

Let's create a document about this

**Comment by zacharyDez** [comment]
Would you want this in the docs folder as a separate file or should it be added to an existing file? I can take this on.

**Comment by vincentsarago** [comment]
@zacharyDez it should be in its own file IMO
