### ISSUE TITLE
add note about the number of request to the STAC API

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler-stacapi#4]
Basically we do 1 request to a STAC API `/search` per tile request.

titiler-stacapi should be used respectfully to any STAC API provider 🙏

**Comment by zacharyDez** [comment]
By respectfully, do you mean limiting the number of requests regarding the load for STAC API providers?

**Comment by vincentsarago** [comment]
yeah, make a note explaining that one tile request will result in one GET request to the STAC API
